const data = [
    {
        name: "PZL P-1",
        image: "http://www.samolotypolskie.pl/uploads/Products/product_2399/PZL_P-11_2prototyp.jpg",
        backgoundImage: "https://static.warthunder.com/upload/image/Polish_News/Artykuly/Dzial_Historyczny/pzl1/PZL_P-1_a7faa165d70d4e896833829015ea6e54.jpg",
        messageBody: `Among the first tasks of newly created in 1928 PZL aircraft works was to design a modern fighter for the Polish Air Force. As a result, a construction team led by the talented young designer Zygmunt Pu³awski designed an all-metal, metal-covered monoplane fighter, designated PZL P.1. Pu³awski's invention was a high gull wing, to give a pilot an optimal view, without an upper wing before his eyes, like in classic parasol monoplanes and biplanes of that time. The wing, supported with struts, could be thin in its root part, at joint with a fuselage. Other new idea was a scissors-like fixed undercarriage, with shock absorbers hidden in the fuselage. The P.1 was powered with a 630 hp Hispano-Suiza inline engine.
        The first prototype was flown in August 1929 by Boles³aw Orliñski. In the first flight, the wing leading edge distorted, but Orliñski saved the aircraft and possibly the whole program. In late 1929, after static trials, the prototype was modified and strengthened. In March 1930, the second prototype was flown (P.1/II). It introduced, among other changes, a revised shape of rudder, similar to Pulawski's next fighters.`
    },
    {
        name: "PZL P-6",
        image: "https://farm5.staticflickr.com/4686/24508087837_7c56694d70.jpg",
        backgoundImage: "http://i16fighter.aviaskins.com/materials/drawings/04.jpg",
        messageBody: `The history of PZL P.6 started in 1928, when a talented designer, Zygmunt Pu³awski designed an all-metal metal-covered monoplane fighter PZL P.1. It introduced a high gull wing, giving a pilot an optimal view. The P.1 was powered with an inline engine, and developed a speed of 302 km/h, but remained a prototype, because it was decided, that a fighter for the Polish Air Force should be powered with a radial engine, licence produced in Poland. Therefore, the next model PZL P.6, was powered with the Bristol Jupiter VI FH radial engine.
        The PZL P.6 was flown for the first time in August 1930 with test pilot Boles³aw Orliñski at the controls. It had a very similar wing to the P.1, but the fuselage was completely redesigned with a modern semi-monocoque configuration introduced that was oval in cross-section, as well, the tail was also changed. As a result of the modifications, the aircraft was over 200 kg lighter.`
    },
    {
        name: "PZL P-7",
        image: "http://lh3.ggpht.com/-4LsEmfecIOI/VHCEQx5fRaI/AAAAAAAAG6w/6WQV6Ov6VAE/s800/p7-2.jpg",
        backgoundImage: "http://www.samolotypolskie.pl/uploads/Products/product_2397/PZL_P-7a.jpg",
        messageBody: `The history of the PZL P.7 began in 1928, when a talented designer named Zygmunt Pu³awski designed an all-metal, metal-covered monoplane fighter, the PZL P.1. It introduced a high gull wing, giving a pilot an optimal view. The wing design was called the "Polish wing" or "Pulawski wing." The P.1 was powered by an inline engine and developed a speed of 302 km/h. But it remained a prototype because a decision was made to use a licence-produced radial engine in the Polish Air Force fighters. So the next model, the PZL P.6, flown in August 1930, was powered by the Bristol Jupiter VI FH radial engine. Both aircraft were well received in the aviation world, with the press recognizing the P.6 as one of the world's top fighters; it won the American National Air Races in August–September 1931.
        The PZL P.6 did not enter production because the next variant, the more advanced PZL P.7, was developed. The first prototype was basically the P.6 with a more powerful Bristol Jupiter VII F engine. Due to the use of a supercharger, it had better performance at higher altitudes. The prototype P.7/I was first flown in October 1930 by Boles³aw Orliñski.[1] Initially, engine cylinders had individual cylinder clearance fairings. After some changes, most noticeably adding a wide Townend ring to the engine and making the tail slimmer, the second prototype P.7/II, built in autumn 1931, was accepted for production with the designation P.7a. It also featured a redesigned wing with slightly increased span, taken from the PZL P.8, and shorter ailerons and smooth upper surfaces, instead of ribbed ones.`
    },
    {
        name: "PZL P-8",
        image: "http://www.samolotypolskie.pl/uploads/Products/product_2398/PZL_P-8_II.jpg",
        backgoundImage: "http://www.samolotypolskie.pl/uploads/Products/product_2398/PZL_P-8_plany.jpg",
        messageBody: `The P.8 was loosely based on the P.1, retaining the slab-sided fuselage and strut braced gull wing characteristic of Pulawski's fighters throughout the 1930s. Despite official preference toward radial engines Pulawski won authority to develop a new fighter powered by V-12 engines up to 800 hp (600 kW). The two fighter designs which emerged were designated P.8 and P.9, re-using the designations of two seaplane designs that had been rejected by the Polish Navy. Two power-plants were fitted to the two prototypes; the P.8/I was fitted with a 640 hp (480 kW) Hispano-Suiza 12Mc; the P.8/II was fitted with a 760 hp (570 kW) Lorraine 12Hfrs Pétrel Chasse.
        The PZL P.11 was a Polish fighter aircraft, designed and constructed during the early 1930s by Warsaw-based aircraft manufacturer PZL. Possessing an all-metal structure, metal-covering, and high-mounted gull wing, the type held the distinction of being widely considered to have briefly been the most advancefighter aircraft of its kind in the world.
        The design of the P.11 commenced during the late 1920s, initially designated as the P.1. The primary individual responsible for its development was Polish aeronautical engineer Zygmunt Pu³awski, who has been attributed as having designed many of its innovative features. While the majority of the world's forces were still using biplanes, the P.1 used a high-mounted and aerodynamically clean gull wing, which provided the pilot with a superior field of view. During September 1929, the first prototype conducted its maiden flight. The design quickly drew international attention; the general layout became commonly known as the "Polish wing" or "Pu³awski wing".`
    },
    {
        name: "PZL P-11",
        image: "https://i.wpimg.pl/O/644x430/d.wpimg.pl/91472684-1467996176/p-11-c.jpg",
        backgoundImage: "http://www.samolotypolskie.pl/uploads/Products/product_2399/PZL_P-11c_rys.jpg",
        messageBody: `The PZL P.11 was a Polish fighter aircraft, designed and constructed during the early 1930s by Warsaw-based aircraft manufacturer PZL. Possessing an all-metal structure, metal-covering, and high-mounted gull wing, the type held the distinction of being widely considered to have briefly been the most advanced fighter aircraft of its kind in the world. The design of the P.11 commenced during the late 1920s, initially designated as the P.1. The primary individual responsible for its development was Polish aeronautical engineer Zygmunt Puławski, who has been attributed as having designed many of its innovative features. While the majority of the world's forces were still using biplanes, the P.1 used a high-mounted and aerodynamically clean gull wing, which provided the pilot with a superior field of view. During September 1929, the first prototype conducted its maiden flight. The design quickly drew international attention; the general layout became commonly known as the "Polish wing" or "Puławski wing". The P.11 served as Poland's primary fighter defence throughout the 1930s, including during the Polish campaign of 1939 by neighbouring Nazi Germany. However, as a consequence of the rapid advances that had been in aircraft design during the late 1930s (seen in such fighters as the Messerschmitt Bf 109), it was outclassed by its rivals at the onset of the war. The majority of the Polish Air Force's P.11s were destroyed during 1939; however, it is believed that as many as 36 were flown to Romania and were subsequently taken over by the Romanian Air Force.`
    },
    {   name: "PZL P-11",
        image: "http://www.samolotypolskie.pl/uploads/Products/product_2401/PZL_P-24C.jpg",
        backgoundImage: "http://www.samolotypolskie.pl/uploads/Products/product_2401/PZL_P-24G.jpg",
        messageBody: `The PZL P.24 was a Polish fighter aircraft, designed during mid-1930s in the PZL factory in Warsaw. It was developed as a dedicated export version of the PZL P.11, a gull wing all-metal fighter designed by Polish aeronautical engineer Zygmunt Puławski. While the P.11 had been powered with a license-built Bristol Mercury radial engine, the terms of this license did not permit PZL to export the engine as well as placing restrictions upon any aircraft that were powered by it. The French engine manufacturer Gnome-Rhône proposed the adoption of their 14K engine to PZL and offered to partially finance the development of a fighter using the engine, which would have no such export restrictions. Accordingly, during early 1932, PZL commenced work on a new derivative of the P.11, which became known as the P.24. The prototypes soon demonstrated favourable performance during testing; notably, the second P.24/II prototype, often referred to as the "Super P.24", established a new world speed record for a radial engine-powered fighter of 414 km/h. The initial production aircraft closely resembled the P.24/II configuration, albeit with some changes such as the adoption of an enclosed cockpit.  `
    }
]

export default data;